version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "mercury-livemap"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1m3ncqlcvoj7u"
s3_prefix = "mercury-livemap"
region = "us-east-1"
capabilities = "CAPABILITY_NAMED_IAM"

